### ISSUE TITLE
Review from team #132 on 07/07/2020

### ISSUE THREAD

**Issue by Prabhakarzx** [RaminMammadzada/using-bootstrap#1]
# Dear @RaminMammadzada you're doing great!

**There are small changes in the header you can fix to make it even better.**

- [ ] There should be space between login and subscribe buttons and three bars in small screen
- [ ] The search section should not move to another line in small screen

- Your project

![NewsSite Ramin](https://user-images.githubusercontent.com/13907212/86797386-3926fe80-c08d-11ea-90ce-4c74cd7d1d28.png)

- The original site

![NewsWeek resize](https://user-images.githubusercontent.com/13907212/86797430-47751a80-c08d-11ea-8a62-d4e46c1c8bfa.png)

### Thank You! :bouquet:

**Comment by RaminMammadzada** [comment]
Thanks for mentioning. It is solved now.
